services:
  postgres:
    image: postgres
    container_name: dsc-postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "${DATABASE}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: